# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jessica Cox
tagline:             'from bench to data science'
description:         
url:                 https://jrcox.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jessica Cox
  url:               https://twitter.com/jessienapcox
  email:             jessica.r.cox13@gmail.com
  github:            https://github.com/jrcox
  linkedin:          https://www.linkedin.com/in/jessica-cox
  
# Custom vars
version:             1.0.0
